library(testthat)
library(PNADCperiods)
# Run from the package root.
results <- devtools::test(".", reporter = "summary")
cat("\n\n=== TEST SUMMARY ===\n")
cat("Passed:", sum(as.data.frame(results)$passed), "\n")
cat("Failed:", sum(as.data.frame(results)$failed), "\n")
cat("Warnings:", sum(as.data.frame(results)$warning), "\n")
cat("Skipped:", sum(as.data.frame(results)$skipped), "\n")
cat("Errors:", sum(as.data.frame(results)$error > 0), "\n")
